services:
  postgres:
    image: postgres:18
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: saga-demo-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  rabbitmq:
    image: rabbitmq:4.2.2-management
    container_name: rabbitmq
    ports:
      - "9000:15672"
      - "5672:5672"
      
  orchestrator:
    image: orchestrator
    build:
      context: .
      dockerfile: Orchestrator/Dockerfile
    depends_on:
      - postgres
      - rabbitmq
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: saga-demo-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      RMQ_HOST: rabbitmq
      RMQ_USER: guest
      RMQ_PASSWORD: guest
      RMQ_PORT: 5672
      RMQ_VHOST: /
    ports:
      - "8080:8080"
